[project]
name = "a-wedge-of-django"
version = "0.1.0"
description = "A wedge of Django with 2024 toolkit"
readme = "README.md"
authors = [
    { name = "Félix Bouazza", email = "fbouazza.dev@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "django>=5.1.4",
]
